/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interfaces.Main;
import Interfaces.Main;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Resources.ConnectionDB;
import static javax.management.Query.gt;
import static javax.management.Query.lt;

/**
 *
 * @author unicuces
 */
public class Activity extends javax.swing.JInternalFrame {

    /**
     * Creates new form Activity
     */
    ConnectionDB cone,cone1, cone2, cone3,cone4;
    DefaultTableModel modelo;

    public Activity() {
        initComponents();
        cone = new ConnectionDB();
        consult("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tit = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_act = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_des = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        lbl_tea = new javax.swing.JLabel();
        lbl_nam_tea = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_id_act = new javax.swing.JLabel();
        cmb_id_cou = new javax.swing.JComboBox<>();
        lbl_cou = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmb_id_per = new javax.swing.JComboBox<>();
        cmb_id_sub = new javax.swing.JComboBox<>();
        lbl_sub = new javax.swing.JLabel();
        cmb_id_ach = new javax.swing.JComboBox<>();
        lbl_ach = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_por = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_qua_act = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_sum_per = new javax.swing.JLabel();
        lbl_sym = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_fil = new javax.swing.JLabel();
        txt_fil = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        lbl_tit.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 20)); // NOI18N
        lbl_tit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tit.setText("Actividades");
        lbl_tit.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_tit, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btn_add.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btn_add.setForeground(new java.awt.Color(0, 102, 153));
        btn_add.setText("Agregar");
        btn_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        tbl_act.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_act);

        txt_des.setColumns(20);
        txt_des.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        txt_des.setRows(5);
        jScrollPane2.setViewportView(txt_des);

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Descripcion");

        lbl_tea.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        lbl_tea.setForeground(new java.awt.Color(0, 102, 153));
        lbl_tea.setText("Docente:");

        lbl_nam_tea.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(234, 234, 234));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Nuevo ID");

        lbl_id_act.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N

        cmb_id_cou.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_id_couItemStateChanged(evt);
            }
        });

        lbl_cou.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        lbl_cou.setForeground(new java.awt.Color(0, 102, 153));
        lbl_cou.setText("Curso");

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Perido");

        cmb_id_per.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_id_perItemStateChanged(evt);
            }
        });

        cmb_id_sub.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_id_subItemStateChanged(evt);
            }
        });

        lbl_sub.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        lbl_sub.setForeground(new java.awt.Color(0, 102, 153));
        lbl_sub.setText("Materia");

        cmb_id_ach.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_id_achItemStateChanged(evt);
            }
        });

        lbl_ach.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        lbl_ach.setForeground(new java.awt.Color(0, 102, 153));
        lbl_ach.setText("Logro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cou)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_id_act, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_id_cou, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(42, 42, 42)
                                .addComponent(cmb_id_per, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_sub)
                        .addGap(36, 36, 36)
                        .addComponent(cmb_id_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_ach)
                        .addGap(45, 45, 45)
                        .addComponent(cmb_id_ach, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_id_act, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_id_cou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_cou)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_id_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sub))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmb_id_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_id_ach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ach))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(237, 234, 234));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Porcentaje");

        txt_por.setToolTipText("");
        txt_por.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_porKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Cant. Act");

        lbl_qua_act.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Suma %");

        lbl_sum_per.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N

        lbl_sym.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        lbl_sym.setText("%");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(69, 69, 69)
                        .addComponent(lbl_qua_act, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_sum_per, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lbl_sym))
                            .addComponent(txt_por, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_por, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lbl_qua_act, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lbl_sum_per, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sym, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbl_fil.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        lbl_fil.setForeground(new java.awt.Color(0, 102, 153));
        lbl_fil.setText("Filtrar");

        txt_fil.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        txt_fil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(lbl_tea, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbl_nam_tea, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lbl_fil, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_fil, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nam_tea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void id() {

        try {
            ResultSet rs = cone.queryDB("SELECT max(ID_ACTIVITIES) FROM activities");

            if (rs.next()) {

                lbl_id_act.setText((rs.getInt("max(ID_ACTIVITIES)") + 1) + "");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void nameTeacher() {
        try {
            ResultSet rs = cone.queryDB("SELECT NAME from person p ,users u "
                    + "WHERE u.ID_PERSON = p.ID_PERSON AND ID_USER = " + Main.idUser);
            if (rs.next()) {
                lbl_nam_tea.setText(rs.getString("NAME"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
public void loadPeriod(){
   
       

        try {
            ResultSet rs = cone.queryDB("SELECT * FROM period");
            while (rs.next()) {
                cmb_id_per.addItem(rs.getString("ID_PERIOD") +"--"+ rs.getString("NAME_PERIOD"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
} 
    public void loadAchievements() {
        cone1 = new ConnectionDB();
        cmb_id_ach.removeAllItems();
        String Courses = cmb_id_cou.getSelectedItem() + "";
        String Divcourses[] = Courses.split("--");
        String idCourses = Divcourses[0];
        String Subjects = cmb_id_sub.getSelectedItem() + "";
        String Divsubjects[] = Subjects.split("--");
        String idSubjects = Divsubjects[0];
        String Periods = cmb_id_per.getSelectedItem() + "";
        String Divperiods[] = Periods.split("--");
        String idPeriods = Divperiods[0];

        try {
            ResultSet rs = cone1.queryDB("SELECT DISTINCT(ID_ACHIEVEMENT) FROM  achievement a "
                    + "INNER JOIN subject s ON s.ID_SUBJECT = a.ID_SUBJECT "
                    + "INNER JOIN teachersxsubjectsxcourses tsc ON tsc.ID_SUBJECT = s.ID_SUBJECT "
                    + "INNER JOIN teacher t ON t.ID_TEACHER = tsc.ID_TEACHERS "
                    + "INNER JOIN person p ON p.ID_PERSON = t.ID_PERSON "
                    + "INNER JOIN users u ON u.ID_PERSON = p.ID_PERSON "
                    + "WHERE tsc.ID_SUBJECT = " + idSubjects + " and tsc.ID_COURSES="+idCourses+" "
                    + "and a.ID_PERIOD = "+idPeriods +" and a.TYPE_ACHIEVEMENTS='academico' and u.ID_USER =" + Main.idUser);
            while (rs.next()) {
                cmb_id_ach.addItem(rs.getString("ID_ACHIEVEMENT"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadCourses() {
        cmb_id_cou.removeAllItems();
       
        try {
            ResultSet rs = cone.queryDB("SELECT DISTINCT(tsc.ID_COURSES), NAME_COURSES FROM teachersxsubjectsxcourses tsc "
                    + "INNER JOIN teacher t ON t.ID_TEACHER = tsc.ID_TEACHERS "
                    + "INNER JOIN courses c ON c.ID_COURSES = tsc.ID_COURSES "
                    + "INNER JOIN person p ON p.ID_PERSON = t.ID_PERSON "
                    + "INNER JOIN users u ON u.ID_PERSON = p.ID_PERSON WHERE u.ID_USER =" + Main.idUser);
            while (rs.next()) {
                cmb_id_cou.addItem(rs.getString("tsc.ID_COURSES") + "--" + rs.getString("NAME_COURSES"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadSubjects() {
         String Courses = cmb_id_cou.getSelectedItem() + "";
        String Divcourses[] = Courses.split("--");
        String idCourses = Divcourses[0];
        try {
            ResultSet rs = cone.queryDB("SELECT DISTINCT(tsc.ID_SUBJECT), s.NAME_SUBJECT FROM teachersxsubjectsxcourses tsc "
                    + "INNER JOIN teacher t ON t.ID_TEACHER = tsc.ID_TEACHERS "
                    + "INNER JOIN courses c ON c.ID_COURSES = tsc.ID_COURSES "
                    + "INNER JOIN subject s ON s.ID_SUBJECT = tsc.ID_SUBJECT "
                    + "INNER JOIN person p ON p.ID_PERSON = t.ID_PERSON "
                    + "INNER JOIN users u ON u.ID_PERSON = p.ID_PERSON WHERE tsc.ID_COURSES="+idCourses+" and u.ID_USER =" + Main.idUser);
                      
            while (rs.next()) {
                cmb_id_sub.addItem(rs.getString("tsc.ID_SUBJECT") + "--" + rs.getString("NAME_SUBJECT"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void consult(String valor) {

        try {
            String titulos[] = {"ID_ACTIVITY", "DESCRIPTION", "PORCENTAGE", "ID_COURSES", "ID_ACHIEVEMENT"};
            modelo = new DefaultTableModel(null, titulos);
            String fila[] = new String[5];
            ResultSet rs = cone.queryDB("SELECT * FROM activities WHERE CONCAT (ID_ACTIVITIES,' ',ID_COURSES,' ',ID_ACHIEVEMENT,' ',DESCRIPTION,' ',PORCENTAGE,' ')LIKE'%" + valor + "%'");
            while (rs.next()) {
                fila[0] = rs.getString("ID_ACTIVITIES");
                fila[1] = rs.getString("DESCRIPTION");
                fila[2] = rs.getString("PORCENTAGE");
                fila[3] = rs.getString("ID_COURSES");
                fila[4] = rs.getString("ID_ACHIEVEMENT");
                modelo.addRow(fila);
                tbl_act.setModel(modelo);
            }
            id();
            loadPeriod();
            nameTeacher();
            loadCourses();
            loadSubjects();
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txt_filKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filKeyReleased
        // TODO add your handling code here:
        consult(txt_fil.getText());
    }//GEN-LAST:event_txt_filKeyReleased

    private void cmb_id_couItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_id_couItemStateChanged
        cone3 = new ConnectionDB();
        try {
            String Courses = cmb_id_cou.getSelectedItem() + "";
            String Divcourses[] = Courses.split("--");
            String idCourses = Divcourses[0];
            // TODO add your handling code here:
            ResultSet rs;
            rs = cone3.queryDB("SELECT count(ID_ACTIVITIES) as cantidad, sum(PORCENTAGE) as suma FROM activities WHERE ID_ACHIEVEMENT = " + cmb_id_ach.getSelectedItem() + " "
                    + "and ID_COURSES = " + idCourses);
            if (rs.next()) {
                lbl_qua_act.setText(rs.getString("cantidad"));
                lbl_sum_per.setText(rs.getString("suma"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmb_id_couItemStateChanged

    private void cmb_id_achItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_id_achItemStateChanged
        // TODO add your handling code here:
        cone2 = new ConnectionDB();

        try {
            String Courses = cmb_id_cou.getSelectedItem() + "";
            String Divcourses[] = Courses.split("--");
            String idCourses = Divcourses[0];
            String Subjects = cmb_id_sub.getSelectedItem() + "";
            String Divsubjects[] = Subjects.split("--");
            String idSubjects = Divsubjects[0];
            ResultSet rs;
            rs = cone2.queryDB("SELECT ach.DESCRIPTION, count(ID_ACTIVITIES) as cantidad, sum(act.PORCENTAGE) as suma FROM activities act, achievement ach "
                    + "WHERE ach.ID_ACHIEVEMENT = act.ID_ACHIEVEMENT AND act.ID_ACHIEVEMENT = " + cmb_id_ach.getSelectedItem() + " AND ID_COURSES = " + idCourses + " "
                    + "AND ach.ID_ACHIEVEMENT = " + cmb_id_ach.getSelectedItem() + " and ach.ID_SUBJECT = " + idSubjects);
            if (rs.next()) {
                lbl_qua_act.setText(rs.getString("cantidad"));
                lbl_sum_per.setText(rs.getString("suma"));
                jTextArea1.setText(rs.getString("ach.DESCRIPTION"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_cmb_id_achItemStateChanged

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            // TODO add your handling code here:
            int suma = 0;
            String idActivity = lbl_id_act.getText();
            String Courses = cmb_id_cou.getSelectedItem() + "";
            String Divcourses[] = Courses.split("--");
            String idCourses = Divcourses[0];
            String idAchiviement = cmb_id_ach.getSelectedItem() + "";
            String txtDesc = txt_des.getText();
            String porcentage = txt_por.getText();

            ResultSet rs = cone.queryDB("SELECT sum(PORCENTAGE) as porcentaje FROM activities WHERE ID_ACHIEVEMENT = " + cmb_id_ach.getSelectedItem() + " "
                    + "and ID_COURSES = " + idCourses);
            if (rs.next()) {
                suma = rs.getInt("porcentaje");
            }
            int porcentaje = 0;
            if (txt_por.getText().isEmpty() || txt_des.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Error: No se ingreso el porcentaje o la descripcion","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                porcentaje = Integer.parseInt(txt_por.getText());
                if ((porcentaje + suma) > 100) {
                    JOptionPane.showMessageDialog(rootPane, "Error: La suma de los porcentajes es mayor a 100%","Error",JOptionPane.ERROR_MESSAGE);
                } else {
                    cone.updateDB("INSERT INTO activities VALUES(" + idActivity + ", '" + txtDesc + "'," + porcentage + "," + idCourses + "," + idAchiviement + ")");
                    consult("");
                }
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_porKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_porKeyTyped
        // TODO add your handling code here:
        int limit=(int)evt.getKeyChar();
if (limit >= 97 && limit<= 122 || limit>=65 && limit<=90){
evt.setKeyChar((char)evt.VK_CLEAR);
JOptionPane.showMessageDialog(rootPane,"No puede ingresar letras","Error",JOptionPane.WARNING_MESSAGE);
}
if(limit==241 || limit==209){
evt.setKeyChar((char)evt.VK_CLEAR);
JOptionPane.showMessageDialog(rootPane,"No puede ingresar letras","Error",JOptionPane.WARNING_MESSAGE);
}
if(limit==10){
txt_por.transferFocus();
}
    }//GEN-LAST:event_txt_porKeyTyped

    private void cmb_id_subItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_id_subItemStateChanged
        // TODO add your handling code here:      
        loadAchievements();
    }//GEN-LAST:event_cmb_id_subItemStateChanged

    private void cmb_id_perItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_id_perItemStateChanged
        // TODO add your handling code here:
        loadAchievements();
    }//GEN-LAST:event_cmb_id_perItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JComboBox<String> cmb_id_ach;
    private javax.swing.JComboBox<String> cmb_id_cou;
    private javax.swing.JComboBox<String> cmb_id_per;
    private javax.swing.JComboBox<String> cmb_id_sub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_ach;
    private javax.swing.JLabel lbl_cou;
    private javax.swing.JLabel lbl_fil;
    private javax.swing.JLabel lbl_id_act;
    private javax.swing.JLabel lbl_nam_tea;
    private javax.swing.JLabel lbl_qua_act;
    private javax.swing.JLabel lbl_sub;
    private javax.swing.JLabel lbl_sum_per;
    private javax.swing.JLabel lbl_sym;
    private javax.swing.JLabel lbl_tea;
    private javax.swing.JLabel lbl_tit;
    private javax.swing.JTable tbl_act;
    private javax.swing.JTextArea txt_des;
    private javax.swing.JTextField txt_fil;
    private javax.swing.JTextField txt_por;
    // End of variables declaration//GEN-END:variables
}
