/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Resources.ConnectionDB;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author unicuces
 */
public class Journeys extends javax.swing.JInternalFrame {

    ConnectionDB cone;
    DefaultTableModel modelo;
    /**
     * Creates new form Journeys
     */
    public Journeys() {
        initComponents();
        cone = new ConnectionDB();
        consult();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_jou = new javax.swing.JLabel();
        lbl_Id = new javax.swing.JLabel();
        lbl_new_id = new javax.swing.JLabel();
        lbl_nam = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jou = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        cmb_jou = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        lbl_jou.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 20)); // NOI18N
        lbl_jou.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jou.setText("JORNADAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_jou, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_jou, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        lbl_Id.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        lbl_Id.setForeground(new java.awt.Color(0, 102, 153));
        lbl_Id.setText("ID");

        lbl_nam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_nam.setForeground(new java.awt.Color(0, 102, 153));
        lbl_nam.setText("Nombre");

        tbl_jou.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_jou);

        btn_add.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btn_add.setForeground(new java.awt.Color(0, 102, 153));
        btn_add.setText("Agregrar");
        btn_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        cmb_jou.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Noche", "Unica" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nam)
                            .addComponent(lbl_Id))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_jou, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(lbl_new_id, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Id)
                    .addComponent(lbl_new_id, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nam)
                    .addComponent(jLabel5)
                    .addComponent(cmb_jou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void id() {
        
        try {
            ResultSet rs = cone.queryDB("SELECT max(ID_JOURNEY) FROM journeys");

            if (rs.next()) {

                lbl_new_id.setText((rs.getInt("max(ID_JOURNEY)") + 1) + "");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Journeys.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void consult() {
          try {
            String titulos[] = {"ID_JOURNEYS", "NOMBRE"};
            modelo = new DefaultTableModel(null, titulos);
            String fila[] = new String[2];
            ResultSet rs = cone.queryDB("SELECT * FROM journeys");
            while (rs.next()) {
                fila[0] = rs.getString("ID_JOURNEY");
                fila[1] = rs.getString("NAME_JOURNEY");
                
                modelo.addRow(fila);
                tbl_jou.setModel(modelo);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Journeys.class.getName()).log(Level.SEVERE, null, ex);
        }
          id();
    }
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String id = lbl_new_id.getText();
        String name = cmb_jou.getSelectedItem()+"";
        cone.updateDB("INSERT INTO journeys VALUES("+id+", "+name+")");
        consult();
    }//GEN-LAST:event_btn_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JComboBox<String> cmb_jou;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_jou;
    private javax.swing.JLabel lbl_nam;
    private javax.swing.JLabel lbl_new_id;
    private javax.swing.JTable tbl_jou;
    // End of variables declaration//GEN-END:variables
}
